# Secret Management Configuration
# Uses 1Password for secure secret storage and retrieval

secret_provider: "1password"
vault: "Private"

# Database Secrets
database:
  url:
    op_path: "op://Private/NEON_DATABASE_STRINGS/arias_v_bianchi_main_db"
    description: "Neon PostgreSQL connection string for ARIBIA Chronicle"

# AI Service Keys
ai:
  anthropic_api_key:
    op_path: "op://Private/ANTHROPIC_API_KEY/credential"
    description: "Anthropic API key for Claude Sonnet 4 analysis"

# ChittyOS Service Authentication
chittyos:
  chittyid_service_token:
    op_path: "op://Private/CHITTYID_SERVICE_TOKEN/credential"
    description: "Service token for ChittyID authentication"

  chittychain_api_key:
    op_path: "op://Private/CHITTYCHAIN_API_KEY/credential"
    description: "API key for ChittyChain blockchain attestations"

  chittybeacon_api_key:
    op_path: "op://Private/CHITTYBEACON_API_KEY/credential"
    description: "API key for ChittyBeacon alerting service"

  chittychronicle_service_token:
    op_path: "op://Private/CHITTYCHRONICLE_SERVICE_TOKEN/credential"
    description: "Service token for ChittyConnect context sharing"

# Session Management
session:
  secret:
    op_path: "op://Private/CHITTYCHRONICLE_SESSION_SECRET/password"
    description: "Express session secret for secure cookie signing"

# OIDC Authentication
oidc:
  client_secret:
    op_path: "op://Private/CHITTYID_CLIENT_SECRET/password"
    description: "ChittyID OIDC client secret"

# Cloud Storage (Optional)
cloud:
  google_cloud_project:
    op_path: "op://Private/GOOGLE_CLOUD_PROJECT/credential"
    description: "Google Cloud project ID for document storage"
    required: false

  google_cloud_storage_bucket:
    op_path: "op://Private/GOOGLE_CLOUD_STORAGE_BUCKET/credential"
    description: "GCS bucket name for evidence files"
    required: false

# Environment Variable Mapping
env_mapping:
  DATABASE_URL: "database.url"
  ANTHROPIC_API_KEY: "ai.anthropic_api_key"
  CHITTYID_SERVICE_TOKEN: "chittyos.chittyid_service_token"
  CHITTYCHAIN_API_KEY: "chittyos.chittychain_api_key"
  CHITTYBEACON_API_KEY: "chittyos.chittybeacon_api_key"
  CHITTYCHRONICLE_SERVICE_TOKEN: "chittyos.chittychronicle_service_token"
  SESSION_SECRET: "session.secret"
  CHITTYID_CLIENT_SECRET: "oidc.client_secret"
  GOOGLE_CLOUD_PROJECT: "cloud.google_cloud_project"
  GOOGLE_CLOUD_STORAGE_BUCKET: "cloud.google_cloud_storage_bucket"

# Security Configuration
security:
  rotate_secrets: true
  rotation_interval: "90d"
  audit_access: true
  encryption_required: true
